# ---- Theme ------ #

# modes
setw -g clock-mode-colour colour1
setw -g mode-style 'fg=#000000 bg=#7894ab bold'

# panes
set -g pane-border-style 'fg=#3b3b3b'
set -g pane-active-border-style 'fg=#3b3b3b'

# statusbar
set-option -g status on
set-option -g status-position top

# statusbar color
set-option -g status-style 'fg=#7894ab bg=#000000'

# messages
set -g message-style 'fg=#000000 bg=#7894ab bold'
