#!/usr/bin/env bash

histfile="$HOME/.cache/cliphist"
placeholder="<NEWLINE>"

highlight() {
    clip=$(xclip -o -selection primary)
    echo "$clip" | xclip -i -selection clipboard
}

output() {
    clip=$(cat)
    echo "$clip" | xclip -selection clipboard
}

write() {
    [ -f "$histfile" ] || notify-send "Creating $histfile"
    touch "$histfile"
    [ -z "$clip" ] && exit 0
    multiline=$(echo "$clip" | sed ':a;N;$!ba;s/\n/'"$placeholder"'/g')
    grep -Fxq "$multiline" "$histfile" || echo "$multiline" >>"$histfile"
    notification="Copied: $multiline"
}

sel() {
    selection=$(tac "$histfile" | dmenu -b -l 5 -i -p "Clipboard history:")
    [ -n "$selection" ] && echo "$selection" | sed "s/$placeholder/\n/g" | xclip -i -selection clipboard && notification="Copied to clipboard!"
}

case "$1" in
add) highlight && write ;;
out) output && write ;;
sel) sel ;;
*)
    printf "$0 | File: $histfile\n\nadd - copies primary selection to clipboard, and adds to history file\nout - pipe commands to copy output to clipboard, and add to history file\nsel - select from history file with dmenu and recopy!\n"
    exit 0
    ;;
esac

[ -z "$notification" ] || notify-send "$notification"
