#!/usr/bin/env bash

bookmark_file="$HOME/.config/qutebrowser/quickmarks"
selected=$(bat "$bookmark_file" | fzf)
url=$(echo "$selected" | cut -d' ' -f2)

if [ -n "$url" ]; then
    firefox-developer-edition "$url" &
fi
