#!/usr/bin/env bash
cols=$(tput cols)
message="(GOOGLE): Eng nge i search duh?"
col=$(( (cols - ${#message}) / 2))
clear
tput cup 0 $col
echo "$message"
tput sgr0
read -r searchString
(setsid zen-browser "https://google.com/search?q=${searchString// /+}" >/dev/null 2>&1 &)
sleep 0.3
disown
exit 0
