#!/usr/bin/env bash
set -euo pipefail

function weirdStuff() {
    destination="/home/$USER/.paswd"

    if [ ! -f "$destination" ]; then
        # Create if the file doesn't exit
        touch "$destination"
    fi

    selected=$(cat "$destination" | awk -F ':' '{ print $1 ":" $2 }' | fzf)

    fullvalue=$(grep "^$selected:" "$destination")
    login=$(echo "$fullvalue" | awk -F ':' '{ print $1 }')
    password=$(echo "$fullvalue" | awk -F ':' '{ print $3 }')

    export DISPLAY=:0

    if command -v xclip &>/dev/null; then
        echo -n "$password" | xclip -selection clipboard
    fi

    if command -v xsel &>/dev/null; then
        echo -n "$password" | xsel -b
    fi

    if command -v notify-send &>/dev/null; then
        notify-send "$login password" "clipboard ah awm tawh e."
    fi
}

weirdStuff
