#!/usr/bin/env bash
set -euo pipefail

destination="/home/$USER/.paswd"

if [ ! -f "$destination" ]; then
    # create the file if not exit
    touch "$destination"
fi

read -p "Enter Platform: " platform
read -p "Enter LogIn ID: " login
read -p "Enter password: " pw

output="$platform:$login:$pw"

echo "$output" >> "$destination"
