#!/usr/bin/env bash
set -euo pipefail

destination="/home/taitesen/.paswd"

read -p "Enter Platform: " platform
read -p "Enter LogIn ID: " login
read -p "Enter password: " pw

output="$platform:$login:$pw"

echo "$output" >> "$destination"
