#!/usr/bin/env bash
bookmark_file="$HOME/.quickmarks"

if [[ ! -f "$bookmark_file" ]]; then
    touch "$bookmark_file"
fi

selected=$(cat "$bookmark_file" | fzf --reverse --border=sharp --border-label=" Quickmarks ")

if [ -z "$selected" ]; then
    exit 1
fi

# Extract URL and ensure it's not empty
url=$(echo "$selected" | cut -d' ' -f2)
if [ -n "$url" ]; then
    (setsid zen-browser "$url" >/dev/null 2>&1 &)
    sleep 0.5
    disown
    exit 0
fi
