#!/usr/bin/env bash

black=#EBBCBA

CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)
if [ "$STATUS" = "Charging" ]; then
	printf "^B4^^c$black^  ^d^ ^C4^$CHARGE%% $STATUS "
else
	printf "^B4^^c$black^  ^d^ ^C4^$CHARGE%% $STATUS "
fi
