#!/usr/bin/env bash
pink="#EBBCBA"
green="#a3b238"

CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)
# if [ "$STATUS" = "Charging" ]; then
# 	printf "^B4^^c$green^  ^d^ ^C4^$CHARGE%% $STATUS "
# else
# 	printf "^B4^^c$green^  ^d^ ^C4^$CHARGE%% $STATUS "
# fi

if [ "$STATUS" = "Charging" ] || [ "$STATUS" = "Full" ]; then
	printf "^B4^^c$green^ 󰂄^d^^C4^$CHARGE%% "
else
	printf "^B4^^c$green^ 󰂃^d^^C4^$CHARGE%% "
fi
