#!/usr/bin/env bash
pink="#EBBCBA"
green="#a3b238"
blue="#7894ab"
light="#9ccfd8"
brown="#bbac9b"

CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)
# if [ "$STATUS" = "Charging" ]; then
# 	printf "^B4^^c$light^  ^d^ ^C4^$CHARGE%% $STATUS "
# else
# 	printf "^B4^^c$light^  ^d^ ^C4^$CHARGE%% $STATUS "
# fi

if [ "$STATUS" = "Charging" ] || [ "$STATUS" = "Full" ]; then
	printf "^B4^^c$brown^  ^d^^C4^$CHARGE%% "
else
	printf "^B4^^c$brown^  ^d^^C4^$CHARGE%% "
fi
