#!/usr/bin/env bash
pink=#EBBCBA
green="#a3b238"
blue="#7894ab"
light="#9ccfd8"
brown="#bbac9b"

clock=$(date '+%I')

case "$clock" in
	"00") icon="󱑊 " ;;
	"01") icon="󱐿 " ;;
	"02") icon="󱑀 " ;;
	"03") icon="󱑁 " ;;
	"04") icon="󱑂 " ;;
	"05") icon="󱑃 " ;;
	"06") icon="󱑄 " ;;
	"07") icon="󱑅 " ;;
	"08") icon="󱑆 " ;;
	"09") icon="󱑇 " ;;
	"10") icon="󱑈 " ;;
	"11") icon="󱑉 " ;;
	"12") icon="󱑊 " ;;
esac


printf "^c$brown^^B4^$icon"
printf "^d^^C4^$(date '+%H:%M')"
