#!/usr/bin/env bash
pink="#EBBCBA"
green="#a3b238"

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print 󰖁 and exit.
[ "$vol" != "${vol%\[MUTED\]}" ] && printf "^c$green^^B1^ 󰖁 ^d^" && exit

vol="${vol#Volume: }"

split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

case 1 in
	$((vol >= 70)) ) icon="  " ;;
	$((vol >= 30)) ) icon="  " ;;
	$((vol >= 1)) ) icon="  " ;;
	* ) printf "^c$green^^B1^ 󰖁 ^d^" && exit ;;
esac

printf "^B1^^c$green^$icon^d^ $vol%%"
