set -g @plugin 'tmux-plugins/tpm'
#set -g default-terminal "tmux-256color"

# unbind-key C-b
set-option -g prefix M-Space
bind-key M-Space send-prefix

set-option -g focus-events on
set-option -sg escape-time 10
set-option -sa terminal-features ',st:RGB'

# passthrough color escape sequences
set -g allow-passthrough 1

unbind %
bind '\' split-window -h -c "#{pane_current_path}" \; resize-pane -R 20
unbind '"'
bind - split-window -v -c "#{pane_current_path}" \; resize-pane -D 5
bind -r m resize-pane -Z

bind-key r source-file ~/.tmux.conf \; display-message "tmux configuration is reloaded!!"

# vi mode in tmux
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi v send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
unbind -T copy-mode-vi mousedragend1pane


bind-key -r -T prefix k resize-pane -U 1
bind-key -r -T prefix j resize-pane -D 1
bind-key -r -T prefix h resize-pane -L 1
bind-key -r -T prefix l resize-pane -R 1

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# ---------------------------------- Theme ---------------------------------- #
bg="#000000"
# default_fg="#ECEFF4"
default_fg="#ebbcba"
# default_fg="#E5E9F0"
session_fg="#a3be8c"
selection_bg="#81A1C1"
selection_fg="#3B4252"
active_pane_border="#6b6b6b"
# active_window_fg="#88C0D0"
active_window_fg="#ebbcba"

set -g status-position bottom
set -g status-left "#[fg=${session_fg},bold,bg=${bg}]  #S"
# set -g status-right "#[fg=${default_fg},bg=${bg}] 󰃮 %Y-%m-%d 󱑒 %H:%M"
set -g status-right " CPU: #{cpu} |  MEM: #{mem} "
set -g status-justify centre
set -g status-left-length 200   # default: 10
set -g status-right-length 200  # default: 10
set-option -g status-style bg=${bg}
set -g window-status-current-format "#[fg=${active_window_fg},bg=default]  #I:#W"
set -g window-status-format "#[fg=${active_pane_border},bg=default] #I:#W"
set -g window-status-last-style "fg=${default_fg},bg=${bg}"
set -g message-command-style bg=default,fg=${default_fg}
set -g message-style bg=default,fg=${default_fg}
set -g mode-style bg=${bg},fg=${default_fg}
set -g pane-active-border-style "fg=${active_pane_border},bg=default"
set -g pane-border-style "fg=${active_pane_border},bg=default"

# --------------------------------  themes -----------------------------------#

run '~/.tmux/plugins/tpm/tpm'

