# ~/.config/starship.toml
[character]
success_symbol = "[󰊬 ](#7894ab)"
error_symbol = "[󰊬 ](bold red)"
vimcmd_symbol = "[vim](#7894ab)"

[directory]
read_only = " 󰌾"
truncation_length = 0
style = "#7894ab"

[git_branch]
format = "[:git\\([$branch]($style)\\)](#bad1c3)"
style= "#ebbcba"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)]($style) (:$ahead_behind:$stashed)]($style)"
style = "#b9a3ba"
conflicted = "::conflicted"
untracked = "::untracked"
modified = "::modified"
staged = "::staged"
renamed = "::renamed"
deleted = "::deleted"
stashed = "::stashed"

[c]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[zig]
symbol = " "
