# vim:ft=kitty

# The basic colors
foreground              #6b6b6b
background              #000000
selection_foreground    #1c1c2b
selection_background    #F5E0DC

# Cursor colors
cursor_shape block
cursor_blink_interval -1
cursor                  #F5E0DC
cursor_text_color       #1c1c2b

# URL underline color when hovering with mouse
url_color               #F5E0DC

# Kitty window border colors
active_border_color     #B4BEFE
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# OS Window titlebar colors
wayland_titlebar_color  #1c1c2b
macos_titlebar_color    #1c1c2b

# Tab bar colors
active_tab_foreground   #11111B
active_tab_background   #CBA6F7
inactive_tab_foreground #CDD6F4
inactive_tab_background #181825
tab_bar_background      #11111B

# Colors for marks (marked text in the terminal)
mark1_foreground #1c1c2b
mark1_background #B4BEFE
mark2_foreground #1c1c2b
mark2_background #CBA6F7
mark3_foreground #1c1c2b
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #3A3C41
color8 #A79397

# red
color1 #3F3C44
color9 #54505B

# green
color2 #ebbcba
color10 #4F5968


# yellow
color3 #6C5D5F
color11 #907B7F


# blue
color4 #2B6E7F
color12 #3A93AA

# magenta
color5 #7B6868
color13 #A48A8B

# cyan
color6 #B3A092
color14 #EFD6C2

# white
color7 #EFE2D8
color15 #EFE2D8
