#include ~/.cache/wal/colors-kitty.conf

font_family     JetBrainsMono NF SemiBold
font_size 	    16.0
bold_font       auto
italic_font      auto
bold_italic_font auto

background_opacity 0.85

confirm_os_window_close 0

enable_audio_bell no

diable_ligature never
window_padding_width 18.0


# Change cursor configuration
cursor_blink_interval 0
cursor_shape block
shell_integration no-cursor

cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Mouse
mouse_hide_wait -1


# Begin kitty theme
include colorscheme.conf
# End kitty theme
