#: Fonts {{{
font_family      JetBrainsMono NF ExtraLight
bold_font        JetBrainsMono NF SemiBold
italic_font      JetBrainsMono NF ExtraLight Italic
bold_italic_font JetBrainsMono NF SemiBold Italic

font_size 18.0

disable_ligatures never

cursor #ebbcba
cursor_text_color #000000
cursor_shape block
shell_integration no-cursor
cursor_blink_interval 0
scrollback_lines 500
scrollback_indicator_opacity 0.3
enable_audio_bell no

sync_to_monitor yes

repaint_delay 5
input_delay 1

window_padding_width 0 20 0

# Color Scheme
foreground #d0d0d0
background #000000
dynamic_background_opacity yes
background_opacity 0.8
background_blur 20
# kitty_mod alt
clear_all_shortcuts yes

map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
map alt+j scroll_line_down
map alt+k scroll_line_up
map alt+shift+j change_font_size all -1.0
map alt+shift+k change_font_size all +1.0
map alt+a set_background_opacity -0.1
map alt+s set_background_opacity +0.1
map ctrl+shift+f5 load_config_file

color0 #26233a
color1 #eb6f92
color2 #9ccf92
color3 #f6c177
color4 #31748f
color5 #c4a7e7
color6 #ebbcba
color7 #e0def4
color8 #6e6a86
color9 #eb6f92
color10 #9ccfd8
color11 #f6c177
color12 #31748f
color13 #c4a7ef
color14 #ebbcba
color15 #e0def4
