#+title: DWM CONFIG
#+PROPERTY: header-args :tangle config.def.h

* TABLE OF CONTENTS :toc:
- [[#appearance][APPEARANCE]]
- [[#tagging][TAGGING]]
- [[#rules][RULES]]
- [[#layouts][LAYOUTS]]
- [[#key-definitions][KEY DEFINITIONS]]
- [[#commands][COMMANDS]]
- [[#keybinds][KEYBINDS]]
- [[#button-definition][BUTTON DEFINITION]]

* APPEARANCE
+ borderpx: Defines the width of the border around windows.
+ snap: Determines the distance a window must be from the screen edge to snap to it.
#+begin_src c
static const unsigned int borderpx  = 0;
static const unsigned int snap      = 0;
#+end_src

+ gappih/gappiv: Horizontal and vertical gaps between windows.
+ gappoh/gappov: Gaps between windows and the edges of the screen.
#+begin_src c
static const unsigned int gappih    = 10;
static const unsigned int gappiv    = 10;
static const unsigned int gappoh    = 10;
static const unsigned int gappov    = 20;
#+end_src

+ smartgaps: If set to 1, there will be no outer gap when there is only one window.
  #+begin_src c
static       int smartgaps          = 0;
  #+end_src

+ showbar: Determines whether to display the status bar.
+ topbar: If set to 1, the bar will be at the top; if 0, at the bottom.
  #+begin_src c
static const int showbar            = 1;
static const int topbar             = 1;
  #+end_src

+ vertpad/sidepad: Padding around the status bar
 #+begin_src c
static const int vertpad            = 10;
static const int sidepad            = 20;
 #+end_src

+ horizpadbar/vertpadbar: Padding inside the status bar itself
#+begin_src c
static const int horizpadbar        = 0;
static const int vertpadbar         = 20;
#+end_src

+ fonts: Specifies fonts to be used in the bar and other UI elements.
+ dmenufont: Font used in the dmenu. But dmenu should be config from dmenu/config.def.h not from here.
  #+begin_src c
static const char *fonts[]          = { "Terminess Nerd Font:size=16:style=Bold:antialias=true:autohint=true", "Font Awesome 6 Free:size=14:antialias=true:autohint=true"};
static const char dmenufont[]       = "monospace:size=10";
  #+end_src

+ Colors: Define various colors used in the UI, typically for foreground and background.
  #+begin_src c
static const char col_gray[]        = "#6b6b6b";
static const char col_black[]       = "#000000";
static const char col_gray3[]       = "#bbbbbb";
static const char col_gray4[]       = "#eeeeee";
static const char col_rose[]        = "#EBBCBA";
  #+end_src

+ colors: Defines color schemes for normal and selected windows.
  * fg : It is a foreground which is the color of the text.
  * bg: It is a background which is the color of the text backgound.
  * border: The color around the element.
  #+begin_src c
static const char *colors[][3]      = {
	/*               fg         bg         border   */
	[SchemeNorm] = { col_gray, col_black, col_black },
	[SchemeSel]  = { col_rose, col_black,  col_black  },
};
  #+end_src

* TAGGING
+ tags: Defines the names of the tags (or workspaces) in the window manager. Each alphabet represents a workspace tag.
 #+begin_src c
static const char *tags[] = { "U", "I", "O", "P", "H", "J", "K", "L", "N" };
 #+end_src

* RULES
+ rules: Specifies how certain applications should behave. Each entry consists of:
    * class: The class of the window (from xprop).
    * instance: The instance name (NULL means any).
    * title: The window title (NULL means any).
    * tags mask: Which tags the window should be assigned to.
    * isfloating: Whether the window should be floating (1 for yes, 0 for no).
    * monitor: Which monitor to place the window on (-1 means the current monitor).
   #+begin_src c
static const Rule rules[] = {
	/* xprop(1):
	 *	WM_CLASS(STRING) = instance, class
	 *	WM_NAME(STRING) = title
	 */
	/* class                 instance    title       tags mask     isfloating   monitor */
	{ "Gimp",                NULL,       NULL,       0,            1,           -1 },
	{ "Firefox",             NULL,       NULL,       1 << 8,       0,           -1 },
	{ "mpv",                 NULL,       NULL,       1 << 8,       0,           -1 },
	{ "VirtualBox Manager",  NULL,       NULL,       1 << 3,       0,           -1 },
};
   #+end_src

* LAYOUTS
+ mfact: Controls the size of the master area (the area for the primary window).
+ nmaster: Number of windows to display in the master area.
+ resizehints: If set to 1, respects the size hints of windows during resizing.
+ lockfullscreen: If set to 1, focuses on fullscreen windows.
+ static const float mfact     = 0.55; /* factor of master area size [0.05..0.95] */
  #+begin_src c
static const float mfact     = 0.55;
static const int nmaster     = 1;    /* number of clients in master area */
static const int resizehints = 0;    /* 1 means respect size hints in tiled resizals */
static const int lockfullscreen = 1; /* 1 will force focus on the fullscreen window */
  #+end_src

+ FORCE_VSPLIT: If enabled, forces a vertical split for specific layouts.
+ vanitygaps.c: An external file included to add features related to gaps between windows.
  #+begin_src c
#define FORCE_VSPLIT 1  /* nrowgrid layout: force two clients to always split vertically */
#include "vanitygaps.c"
  #+end_src

+ layouts: Defines the different window layouts available. Each entry consists of:
        * symbol: Symbol representing the layout (can include icons).
        * arrange function: The function that implements the layout behavior.
 #+begin_src c
static const Layout layouts[] = {
	/* symbol     arrange function */
	{ "  ",  tile },    /* first entry is default */
	{ "  ",  monocle },
	{ "  ",  spiral },
	{ "  ",  dwindle },
	{ "  ",  deck },
	{ "  ",  bstack },
	{ "  ",  bstackhoriz },
	{ " 󰕰 ",  grid },
	{ " 󰾍 ",  nrowgrid },
	{ " 󱗼 ",  horizgrid },
	{ ":::",  gaplessgrid },
	{ " 󰕭 ",  centeredmaster },
	{ "  ",  centeredfloatingmaster },
	{ "  ",  NULL },    /* no layout function means floating behavior */
	{ NULL,       NULL },
};
 #+end_src

* KEY DEFINITIONS
+ MODKEY: Defines the modifier key (often the Super/Windows key).
+ TAGKEYS: A macro to define keybindings for switching, toggling, and tagging windows with specific tags.
  #+begin_src c
#define MODKEY Mod4Mask
#define TAGKEYS(KEY,TAG) \
	{ MODKEY,                       KEY,      view,           {.ui = 1 << TAG} }, \
	{ MODKEY|Mod1Mask,              KEY,      toggleview,     {.ui = 1 << TAG} }, \
	{ MODKEY|ShiftMask,             KEY,      tag,            {.ui = 1 << TAG} }, \
	{ MODKEY|ControlMask|ShiftMask, KEY,      toggletag,      {.ui = 1 << TAG} },
  #+end_src

+ SHCMD: A macro for creating command structures to spawn shell commands.
#+begin_src c
#define SHCMD(cmd) { .v = (const char*[]){ "/bin/sh", "-c", cmd, NULL } }
#+end_src

* COMMANDS
This section defines commands that can be executed via keybindings or button clicks. Each command is represented as an array of strings, where the first element is the command to run, and the subsequent elements are arguments.

+ dmenumon: A string that specifies the monitor on which dmenu will appear. It can be manipulated to run dmenu on different monitors.
  #+begin_src c
static char dmenumon[2] = "0"; /* component of dmenucmd, manipulated in spawn() */
  #+end_src

+ termcmd: Command to open a terminal. In this case, it's set to launch st (Simple Terminal). The NULL at the end indicates the end of the command arguments.
  #+begin_src c
static const char *termcmd[]  = { "st", NULL };
  #+end_src

+ dmenucmd: Command to launch dmenu, a dynamic menu for X. This is used to run applications.
  #+begin_src c
static const char *dmenucmd[] = { "dmenu_run", NULL };
  #+end_src

+ screenshot: Command to take a screenshot using flameshot. The argument "gui" opens the graphical user interface for flameshot.
  #+begin_src c
static const char *screenshot[]  = { "flameshot", "gui", NULL };
  #+end_src

+ toggleblur: Command to toggle a blur effect on the desktop. This corresponds to a script that I have written to manipulate the picom.conf file to toggle blur and unblur on the fly .
  #+begin_src c
static const char *toggleblur[]  = { "toggleblur", NULL };
  #+end_src

+ browser: Command to launch qutebrowser, a keyboard-focused browser.
 #+begin_src c
static const char *browser[] = { "qutebrowser", NULL };
 #+end_src

+ emacs: Command to open Emacs using emacsclient. The -c flag creates a new frame, and -a "emacs" specifies the alternative editor to start if the Emacs server is not running.
  #+begin_src c
static const char *emacs[] = { "emacsclient", "-c", "-a \"emacs\"", NULL };
  #+end_src

* KEYBINDS
#+begin_src c
static const Key keys[] = {
	/* modifier                     key        function        argument */
	{ MODKEY,                       XK_w,      spawn,          {.v = browser } },
	{ MODKEY,                       XK_e,      spawn,          {.v = emacs } },
	{ MODKEY,                       XK_space,  spawn,          {.v = dmenucmd } },
	{ MODKEY,                       XK_Return, spawn,          {.v = termcmd } },
        { MODKEY|ShiftMask,             XK_s,      spawn,          {.v   =   screenshot    }     },
        { MODKEY|ShiftMask,             XK_b,      spawn,          {.v   =   toggleblur    }     },
	{ MODKEY,                       XK_b,      togglebar,      {0} },
	{ MODKEY,                       XK_period, focusstack,     {.i = +1 } },
	{ MODKEY,                       XK_comma,  focusstack,     {.i = -1 } },
	{ MODKEY,                       XK_Up,     incnmaster,     {.i = +1 } },
	{ MODKEY,                       XK_Down,   incnmaster,     {.i = -1 } },
	{ MODKEY,                       XK_bracketleft,      setmfact,       {.f = -0.01} },
	{ MODKEY,                       XK_bracketright,      setmfact,       {.f = +0.01} },
	{ MODKEY|ShiftMask,             XK_bracketleft,      setcfact,       {.f = +0.25} },
	{ MODKEY|ShiftMask,             XK_bracketright,      setcfact,       {.f = -0.25} },
	{ MODKEY|ShiftMask,             XK_Return, zoom,           {0} },
	{ MODKEY|Mod1Mask,              XK_3,      incrgaps,       {.i = +1 } },
	{ MODKEY|Mod1Mask|ShiftMask,    XK_3,      incrgaps,       {.i = -1 } },
	{ MODKEY|Mod1Mask,              XK_4,      incrigaps,      {.i = +1 } },
	{ MODKEY|Mod1Mask|ShiftMask,    XK_4,      incrigaps,      {.i = -1 } },
	{ MODKEY|Mod1Mask,              XK_5,      incrogaps,      {.i = +1 } },
	{ MODKEY|Mod1Mask|ShiftMask,    XK_5,      incrogaps,      {.i = -1 } },
	{ MODKEY|Mod1Mask,              XK_6,      incrihgaps,     {.i = +1 } },
	{ MODKEY|Mod1Mask|ShiftMask,    XK_6,      incrihgaps,     {.i = -1 } },
	{ MODKEY|Mod1Mask,              XK_7,      incrivgaps,     {.i = +1 } },
	{ MODKEY|Mod1Mask|ShiftMask,    XK_7,      incrivgaps,     {.i = -1 } },
	{ MODKEY|Mod1Mask,              XK_8,      incrohgaps,     {.i = +1 } },
	{ MODKEY|Mod1Mask|ShiftMask,    XK_8,      incrohgaps,     {.i = -1 } },
	{ MODKEY|Mod1Mask,              XK_9,      incrovgaps,     {.i = +1 } },
	{ MODKEY|Mod1Mask|ShiftMask,    XK_9,      incrovgaps,     {.i = -1 } },
	{ MODKEY|Mod1Mask,              XK_0,      togglegaps,     {0} },
	{ MODKEY|Mod1Mask|ShiftMask,    XK_0,      defaultgaps,    {0} },
	{ MODKEY,                       XK_0,      view,           {0} },
	{ MODKEY,                       XK_c,      killclient,     {0} },
	{ MODKEY|ControlMask,		    XK_comma,  cyclelayout,    {.i = -1 } },
	{ MODKEY|ControlMask,           XK_period, cyclelayout,    {.i = +1 } },
	{ MODKEY|ShiftMask,             XK_space,  setlayout,      {0} },
	{ MODKEY,                       XK_Tab,    view,           {.ui = ~0 } },
	{ MODKEY|ShiftMask,             XK_0,      tag,            {.ui = ~0 } },
	{ MODKEY,                       XK_KP_Left,  focusmon,       {.i = -1 } },
	{ MODKEY,                       XK_KP_Right, focusmon,       {.i = +1 } },
	{ MODKEY|ShiftMask,             XK_KP_Left,  tagmon,         {.i = -1 } },
	{ MODKEY|ShiftMask,             XK_KP_Right, tagmon,         {.i = +1 } },
	TAGKEYS(                        XK_u,                      0)
	TAGKEYS(                        XK_i,                      1)
	TAGKEYS(                        XK_o,                      2)
	TAGKEYS(                        XK_p,                      3)
	TAGKEYS(                        XK_h,                      4)
	TAGKEYS(                        XK_j,                      5)
	TAGKEYS(                        XK_k,                      6)
	TAGKEYS(                        XK_l,                      7)
	TAGKEYS(                        XK_n,                      8)
	{ MODKEY|ShiftMask,             XK_q,      quit,           {0} },
};
#+end_src

* BUTTON DEFINITION
 Click can be ClkTagBar, ClkLtSymbol, ClkStatusText, ClkWinTitle, ClkClientWin, or ClkRootWin
 #+begin_src c
static const Button buttons[] = {
	/* click                event mask      button          function        argument */
	{ ClkLtSymbol,          0,              Button1,        setlayout,      {0} },
	{ ClkLtSymbol,          0,              Button3,        setlayout,      {.v = &layouts[2]} },
	{ ClkWinTitle,          0,              Button2,        zoom,           {0} },
	{ ClkStatusText,        0,              Button2,        spawn,          {.v = termcmd } },
	{ ClkClientWin,         MODKEY,         Button1,        movemouse,      {0} },
	{ ClkClientWin,         MODKEY,         Button2,        togglefloating, {0} },
	{ ClkClientWin,         MODKEY,         Button3,        resizemouse,    {0} },
	{ ClkTagBar,            0,              Button1,        view,           {0} },
	{ ClkTagBar,            0,              Button3,        toggleview,     {0} },
	{ ClkTagBar,            MODKEY,         Button1,        tag,            {0} },
	{ ClkTagBar,            MODKEY,         Button3,        toggletag,      {0} },
};
 #+end_src
